# Generated by Django 5.1.1 on 2025-03-02 20:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Restaurant Name')),
                ('description', models.TextField(help_text='Detailed description of the restaurant', verbose_name='Description')),
                ('cuisine_type', models.CharField(choices=[('ASIAN', 'Asian'), ('ITALIAN', 'Italian'), ('MEXICAN', 'Mexican'), ('AMERICAN', 'American'), ('INDIAN', 'Indian'), ('MEDITERRANEAN', 'Mediterranean'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Cuisine Type')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('price_range', models.CharField(choices=[('$', 'Budget'), ('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Fine Dining')], default='$$', max_length=4, verbose_name='Price Range')),
                ('average_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Average Rating')),
                ('opentime', models.TimeField(verbose_name='Opening Hour')),
                ('closetime', models.TimeField(verbose_name='Closing Hour')),
                ('delivery_available', models.BooleanField(default=False, verbose_name='Delivery Available')),
                ('takeout_available', models.BooleanField(default=False, verbose_name='Takeout Available')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('street_address', models.CharField(blank=True, max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-created_at'],
            },
        ),
    ]
