# Generated by Django 5.1.1 on 2024-09-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='longitude',
            new_name='longtitude',
        ),
    ]
