# Generated by Django 5.1.1 on 2025-03-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
