# Generated by Django 5.0.2 on 2024-02-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='rates',
            new_name='rate',
        ),
    ]
