# Generated by Django 5.0.2 on 2024-02-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_category_location_ratings_restaurant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Customer',
            field=models.ManyToManyField(blank=True, to='restaurant.user'),
        ),
    ]
