# Generated by Django 5.1.1 on 2025-09-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_approvedrestaurant_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='establishment_type',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('CAFE', 'Cafe'), ('BAR', 'Bar & Pub'), ('FAST_FOOD', 'Fast Food'), ('BAKERY', 'Bakery'), ('COFFEE_SHOP', 'Coffee Shop'), ('FOOD_TRUCK', 'Food Truck'), ('TAKEAWAY', 'Takeaway'), ('ICE_CREAM', 'Ice Cream Shop'), ('BUFFET', 'Buffet'), ('FINE_DINING', 'Fine Dining'), ('CASUAL_DINING', 'Casual Dining'), ('DELI', 'Deli'), ('JUICE_BAR', 'Juice Bar'), ('OTHER', 'Other')], default='RESTAURANT', max_length=50, verbose_name='Establishment Type'),
        ),
        migrations.AlterField(
            model_name='approvedrestaurant',
            name='cuisine_type',
            field=models.CharField(choices=[('ASIAN', 'Asian'), ('ITALIAN', 'Italian'), ('MEXICAN', 'Mexican'), ('AMERICAN', 'American'), ('INDIAN', 'Indian'), ('MEDITERRANEAN', 'Mediterranean'), ('FRENCH', 'French'), ('JAPANESE', 'Japanese'), ('CHINESE', 'Chinese'), ('THAI', 'Thai'), ('KOREAN', 'Korean'), ('VIETNAMESE', 'Vietnamese'), ('GREEK', 'Greek'), ('TURKISH', 'Turkish'), ('MIDDLE_EASTERN', 'Middle Eastern'), ('LATIN', 'Latin American'), ('AFRICAN', 'African'), ('SEAFOOD', 'Seafood'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50, verbose_name='Cuisine Type'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(choices=[('ASIAN', 'Asian'), ('ITALIAN', 'Italian'), ('MEXICAN', 'Mexican'), ('AMERICAN', 'American'), ('INDIAN', 'Indian'), ('MEDITERRANEAN', 'Mediterranean'), ('FRENCH', 'French'), ('JAPANESE', 'Japanese'), ('CHINESE', 'Chinese'), ('THAI', 'Thai'), ('KOREAN', 'Korean'), ('VIETNAMESE', 'Vietnamese'), ('GREEK', 'Greek'), ('TURKISH', 'Turkish'), ('MIDDLE_EASTERN', 'Middle Eastern'), ('LATIN', 'Latin American'), ('AFRICAN', 'African'), ('SEAFOOD', 'Seafood'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Cuisine Type'),
        ),
    ]
