# Generated by Django 5.1.1 on 2024-09-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_longitude_restaurant_longtitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
