# Generated by Django 5.1.1 on 2025-09-14 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_establishment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlacesRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_id', models.CharField(max_length=255, unique=True, verbose_name='Google Place ID')),
                ('name', models.CharField(max_length=200, verbose_name='Restaurant Name')),
                ('formatted_address', models.TextField(blank=True, verbose_name='Formatted Address')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('google_url', models.URLField(blank=True, verbose_name='Google Maps URL')),
                ('cuisine_type', models.CharField(choices=[('ASIAN', 'Asian'), ('ITALIAN', 'Italian'), ('MEXICAN', 'Mexican'), ('AMERICAN', 'American'), ('INDIAN', 'Indian'), ('MEDITERRANEAN', 'Mediterranean'), ('FRENCH', 'French'), ('JAPANESE', 'Japanese'), ('CHINESE', 'Chinese'), ('THAI', 'Thai'), ('KOREAN', 'Korean'), ('VIETNAMESE', 'Vietnamese'), ('GREEK', 'Greek'), ('TURKISH', 'Turkish'), ('MIDDLE_EASTERN', 'Middle Eastern'), ('LATIN', 'Latin American'), ('AFRICAN', 'African'), ('SEAFOOD', 'Seafood'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='Cuisine Type')),
                ('establishment_type', models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('CAFE', 'Cafe'), ('BAR', 'Bar & Pub'), ('FAST_FOOD', 'Fast Food'), ('BAKERY', 'Bakery'), ('COFFEE_SHOP', 'Coffee Shop'), ('FOOD_TRUCK', 'Food Truck'), ('TAKEAWAY', 'Takeaway'), ('ICE_CREAM', 'Ice Cream Shop'), ('BUFFET', 'Buffet'), ('FINE_DINING', 'Fine Dining'), ('CASUAL_DINING', 'Casual Dining'), ('DELI', 'Deli'), ('JUICE_BAR', 'Juice Bar'), ('OTHER', 'Other')], default='RESTAURANT', max_length=50, verbose_name='Establishment Type')),
                ('price_level', models.IntegerField(blank=True, help_text='0-4 scale from Google', null=True, verbose_name='Price Level')),
                ('price_range', models.CharField(choices=[('$', 'Budget'), ('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Fine Dining')], default='$$', max_length=4, verbose_name='Price Range')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Google Rating')),
                ('user_ratings_total', models.IntegerField(default=0, verbose_name='Total Reviews')),
                ('opening_hours_text', models.TextField(blank=True, help_text='Weekday text from Google', verbose_name='Opening Hours')),
                ('is_open_now', models.BooleanField(blank=True, null=True, verbose_name='Open Now')),
                ('is_open_24_hours', models.BooleanField(default=False, verbose_name='Open 24 Hours')),
                ('delivery_available', models.BooleanField(default=False, verbose_name='Delivery Available')),
                ('takeout_available', models.BooleanField(default=False, verbose_name='Takeout Available')),
                ('business_status', models.CharField(default='OPERATIONAL', max_length=50, verbose_name='Business Status')),
                ('google_types', models.JSONField(blank=True, default=list, verbose_name='Google Place Types')),
                ('photo_references', models.JSONField(blank=True, default=list, verbose_name='Photo References')),
                ('reviews_data', models.JSONField(blank=True, default=list, verbose_name='Reviews Data')),
                ('last_updated_from_google', models.DateTimeField(auto_now=True, verbose_name='Last Updated from Google')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cache_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Cache Expires At')),
            ],
            options={
                'verbose_name': 'Google Places Restaurant',
                'verbose_name_plural': 'Google Places Restaurants',
                'ordering': ['-rating', '-user_ratings_total'],
                'indexes': [models.Index(fields=['google_place_id'], name='restaurant__google__44fcdf_idx'), models.Index(fields=['latitude', 'longitude'], name='restaurant__latitud_3cf400_idx'), models.Index(fields=['cuisine_type'], name='restaurant__cuisine_23ec98_idx'), models.Index(fields=['establishment_type'], name='restaurant__establi_80ee7e_idx'), models.Index(fields=['rating'], name='restaurant__rating_73359f_idx')],
            },
        ),
    ]
