# Generated by Django 5.0.2 on 2024-03-04 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_categorys_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rate',
            field=models.PositiveIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
