# Generated by Django 5.0.2 on 2024-03-04 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rate',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
